pub mod chunker;
pub mod database;
pub mod document;
pub mod embedding;
pub use embedding::{EmbeddingClient, EmbeddingProvider};
pub mod config;
pub mod engine;
pub mod error;
pub use config::EmbeddingConfig;
pub mod filter;
pub use filter::MetadataFilter;
pub mod diagnostics;
pub mod evaluation;
pub mod metadata;
pub mod pipeline;
pub mod retrieval;
pub mod search_result;
pub mod similarity;
pub mod tokenizer;
pub mod vector;
pub use diagnostics::RetrievalDiagnostics;
pub mod api;
pub use database::Database;
pub use document::{Document, load_from_file};
pub use engine::RecallEngine;
pub use retrieval::{Retriever, SearchOptions};
pub use search_result::SearchResult;
